<?php
/**
 * @var $this Istans_Quickorder_Block_Index
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<div class='quickorder'>
    <form id="edge_quickorder" name="edge_quickorder" method='post' action="<?php echo $this->getUrl('quickorder/index/addToCart')?>">
        <table id="example" class="display" style="width:100%">
            <thead>
                <tr>
                    <th width="5%"><?php echo $this->__('Sku');?></th>
                    <th><?php echo $this->__('Product Name');?></th>
                    <th width="10%"><?php echo $this->__('Availability');?></th>
                    <th width="11%"><?php echo $this->__('Price');?></th>
                    <th width="10%"><?php echo $this->__('Qty');?></th>
                    <th width="12%"><?php echo $this->__('Total');?></th>
                </tr>
            </thead>
        </table>
        <div class="actions">
            <button type="button" class='button show-popup-quick-order miniCartWrap' title='<?php echo $this->__('Checkout'); ?>'>
                <span><?php echo $this->__('Checkout'); ?></span>
            </button>
        </div>
    </form>
</div>
<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('#example').DataTable({
            "processing": true,
            "serverSide": true,
            "ajax": "<?php echo $this->getUrl('quickorder/index/products'); ?>",
            "lengthMenu": [[10, 25, 50], [10, 25, 50]],
            "createdRow": function ( row, data, index ) {
                jQuery('td', row).eq(0).html('<a class="product-item-link" href="' + data['product_url'] + '">' + data['sku'] + '</a>');
                jQuery('td', row).eq(1).html('<a class="product-item-link" href="' + data['product_url'] + '">' + data['name'] + '</a>');
                if (!data['available'] || data['qty'] <= 0) {
                    jQuery(row).addClass('outstock');
                }
                var dtQtyElement = jQuery('<div/>', {
                    class: 'field qty',
                });
                var dtQtyElementInnerHtml = '';
                if (data['available'] === true && data['qty'] > 0) {
                    jQuery('td', row).eq(2).html('<span class="stock"><?php echo $this->__('In stock'); ?></span>');
                    dtQtyElementInnerHtml = '<div class="clearfix">\n' +
                        '    <div class="actions">\n' +
                        '        <button type="button"\n' +
                        '                class="button btn-cart qty_dec"\n' +
                        '                onclick="setLocation(\'' + data['add_to_cart_url'] + '\')"\n' +
                        '                data-min="1">\n' +
                        '                    <i class="fa fa-minus"></i>\n' +
                        '        </button>\n' +
                        '    </div>\n' +
                        '    <input type="hidden" class="input-sku" name="product[' + data['entity_id'] + '][sku]" value="' + data['sku'] + '">\n' +
                        '    <input id="cart-' + data['entity_id'] + '-qty"\n' +
                        '           name="product[' + data['entity_id'] + '][qty]"\n' +
                        '           value="0"\n' +
                        '           type="text"\n' +
                        '           size="4"\n' +
                        '           class="input-text qty"\n' +
                        '           maxlength="12"\n' +
                        '           max="' + data['max_qty'] + '" />\n' +
                        '    <div class="actions">\n' +
                        '        <button type="button"\n' +
                        '                class="button btn-cart qty_inc"\n' +
                        '                onclick="setLocation(\'' + data['add_to_cart_url'] + '\')">\n' +
                        '                    <i class="fa fa-plus"></i>\n' +
                        '        </button>\n' +
                        '    </div>\n' +
                        '</div>';
                } else {
                    jQuery('td', row).eq(2).html('<span class="backorder"><?php echo $this->__('Out of stock'); ?></span>');
                    dtQtyElementInnerHtml = '--';
                }
                jQuery(dtQtyElement).eq(0).html(dtQtyElementInnerHtml);
                jQuery('td', row).eq(4).html(jQuery(dtQtyElement).eq(0).html());
            },
            "columnDefs": [
                {
                    "targets": 4,
                    "orderable": false
                },
                {
                    "targets": 5,
                    "orderable": false
                }
            ],
            "columns": [
                { "data": "sku" },
                { "data": "name" },
                { "data": "available" },
                { "data": "price" },
                { "data": "qty" },
                { "data": "total" }
            ]
        });
    });
</script>